version: '3'
services:
        proxygen:
            image: 'jwilder/docker-gen'
            container_name: 'proxygen'
            volumes:
                - '/var/run/docker.sock:/tmp/docker.sock:ro'
                - '/var/lib/docker/data/proxygen:/templates'
                - '/var/lib/docker/data/nginx/etc/nginx/conf.d:/conf'
            command: '-watch -notify-sighup=proxy /templates/proxy.tmpl /conf/proxy.conf'
            tty: true
            stdin_open: true
            restart: always
            environment: 
            - COMPOSE_PROJECT_NAME:proxy
            networks: 
            - proxy
       
        nginx:
            image: 'nginx'
            container_name: 'proxy'
            volumes:
                - '/var/lib/docker/data/nginx/etc/nginx/conf.d:/etc/nginx/conf.d:ro'
            ports:
                - '81:81'
            tty: true
            stdin_open: true
            restart: always
            environment: 
            - COMPOSE_PROJECT_NAME:proxy
            networks: 
            - proxy

networks:
  proxy:
    driver: bridge
