version: '3'

volumes:
  vol-nginx-conf: {}

services:
        proxygen:
            image: 'jwilder/docker-gen'
            container_name: 'proxygen'
            volumes:
                - '/var/run/docker.sock:/tmp/docker.sock:ro'
                - ./:/templates
                - vol-nginx-conf:/conf
            command: '-watch -notify-sighup=proxy /templates/proxy.tmpl /conf/proxy.conf'
            tty: true
            stdin_open: true
            restart: always
            environment: 
            - COMPOSE_PROJECT_NAME:proxy
            networks: 
            - proxy
       
        nginx:
            image: 'nginx'
            container_name: 'proxy'
            volumes:
                - vol-nginx-conf:/etc/nginx/conf.d:ro
            ports:
                - '81:81'
            tty: true
            stdin_open: true
            restart: always
            environment: 
            - COMPOSE_PROJECT_NAME:proxy
            networks: 
            - proxy

networks:
  proxy:
    driver: bridge
